apiVersion: v1
kind: Service
metadata:
  name: ubuntu
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ubuntu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: riscv64/ubuntu:latest
        command: ["sleep"]
        args: ["infinity"]
